# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: malik-hubspot

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  timeout: 10
  memorySize: 256
  logRetentionInDays: 14

functions:
  sync:
    handler: handler.sync
